	 <div class="container">
    <h1>Parents</h1>
    <p>Steve Jobs's biological father, Abdulfattah "John" Jandali (Arabic: عبد الفتاح الجندلي) (b. 1931), grew up in Homs, Syria and was born into an Arab Muslim household.[10] Jandali is the son of a self-made millionaire who did not go to college and a mother who was a traditional housewife.[10] While an undergraduate at the American University of Beirut, Lebanon, he was a student activist and spent time in jail for his political activities.[10] Although Jandali initially wanted to study law, he eventually decided to study economics and political science.[10] He pursued a PhD in the latter subject at the University of Wisconsin, where he met Joanne Carole Schieble, a Catholic of Swiss and German descent, who grew up on a farm in Wisconsin.[11][10][12] As a doctoral candidate, Jandali was a teaching assistant for a course Schieble was taking, although both were the same age.[13] Jobs's full biological sister (Mona Simpson), notes that her maternal grandparents were not happy that their daughter was dating Jandali: "it wasn't that he was Middle-Eastern so much as that he was a Muslim. But there are a lot of Arabs in Michigan and Wisconsin. So it's not that unusual."[13] Walter Isaacson, Steve Jobs's official biographer, additionally states that Schieble's father "threatened to cut Joanne off completely" if she continued the relationship.[11]
Jobs's adoptive father, Paul Reinhold Jobs (1922–1993), grew up in a Calvinist household,[14] the son of an "alcoholic and sometimes abusive" father.[11] The family lived on a farm in Germantown, Wisconsin.[11][14] Paul bore an ostensible resemblance to James Dean; he had tattoos, dropped out of high school, and traveled around the Midwest for several years during the 1930s looking for work.[11][14] He eventually joined the United States Coast Guard as an engine-room machinist.[14] After World War II, Paul Jobs decided to leave the Coast Guard when his ship docked in San Francisco.[14] He made a bet that he would find his wife in San Francisco and promptly went on a blind date with Clara Hagopian (1924–1986). They were engaged ten days later and married in 1946.[11] Clara, the daughter of Armenian immigrants, grew up in San Francisco and had been married before, but her husband had been killed in the war. After a series of moves, Paul and Clara settled in San Francisco's Sunset District in 1952.[11] As a hobby, Paul Jobs rebuilt cars, but his career was as a "repo man", which suited his "aggressive, tough personality."[14] Meanwhile, their attempts to start a family were halted after Clara had an ectopic pregnancy, leading them to consider adoption in 1955.[11]
</p>
<h1>Birth</h1>
<p>
"Of all the inventions of humans, the computer is going to rank near or at the top as history unfolds and we look back. It is the most awesome tool that we have ever invented. I feel incredibly lucky to be at exactly the right place in Silicon Valley, at exactly the right time, historically, where this invention has taken form."
—Steve Jobs, 1995. From the documentary, Steve Jobs: The Lost Interview.[15]
Schieble became pregnant in 1954 when she and Jandali spent the summer with his family in Homs, Syria. Jandali has stated that he "was very much in love with Joanne ... but sadly, her father was a tyrant, and forbade her to marry me, as I was from Syria. And so she told me she wanted to give the baby up for adoption."[16] Jobs told his official biographer that Schieble's father was dying at the time, Schieble did not want to aggravate him, and both felt that at 23 they were too young to marry.[11] In addition, as there was a strong stigma against bearing a child out of wedlock and raising it as a single mother, and as abortions were illegal and dangerous, adoption was the only option women had in the United States in 1954.[14] According to Jandali, Schieble deliberately did not involve him in the process: "without telling me, Joanne upped and left to move to San Francisco to have the baby without anyone knowing, including me ... she did not want to bring shame onto the family and thought this was the best for everyone."[16] Schieble put herself in the care of a "doctor who sheltered unwed mothers, delivered their babies, and quietly arranged closed adoptions."[11]
Schieble gave birth to Jobs on February 24, 1955, in San Francisco and chose an adoptive couple for him that was "Catholic, well-educated, and wealthy."[17] The couple changed their mind, however, and decided to adopt a girl instead.[17] The baby boy was then placed with the Bay Area blue collar couple Paul and Clara Jobs, neither of whom had a college education, and Schieble refused to sign the adoption papers.[11] She then took the matter to court in an attempt to have her baby placed with a different family[17] and only consented to releasing the baby to Paul and Clara after they promised that he would attend college.[11] When Steve Jobs was in high school, his mother Clara admitted to his girlfriend, 17-year-old Chrisann Brennan, that she "was too frightened to love [Steve] for the first six months of his life ... I was scared they were going to take him away from me. Even after we won the case, Steve was so difficult a child that by the time he was two I felt we had made a mistake. I wanted to return him."[17] When Chrisann shared his mother's comment with Steve, he stated that he was already aware of that[17] and would later say he was deeply loved and indulged by Paul and Clara.[18] Many years later, Steve Jobs's wife Laurene also noted that "he felt he had been really blessed by having the two of them as parents."[18] Jobs would become upset when Paul and Clara were referred to as "adoptive parents" as they "were my parents 1,000%."[11] With regard to his biological parents, Jobs referred to them as "my sperm and egg bank. That's not harsh, it's just the way it was, a sperm bank thing, nothing more."[11] Jandali has also stated that "I really am not his dad. Mr. and Mrs. Jobs are, as they raised him. And I don't want to take their place."[16]</p>
</div>
